[build]
builder = "nixpacks"

[deploy]
startCommand = "python cost_monitor.py & python app.py"  # MONITOR PRIMEIRO!

[services]
name = "web"
[services.ports]
port = 10000

# LIMITES EXPLÍCITOS
[services.scaling]
min = 1
max = 1  # SÓ 1 INSTÂNCIA!

[services.resources]
cpu = 256    # MÍNIMO
memory = 512 # MÍNIMO