services:
  - type: web
    name: brazmar-news-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    pythonVersion: "3.11.9" 
    envVars:
      - key: GEMINI_API_KEY
        sync: false